import { NgModule, ModuleWithProviders } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  AutoCompleteModule,
  AccordionModule,
  ButtonModule,
  BreadcrumbModule,
  BlockUIModule,
  CalendarModule,
  CaptchaModule,
  CarouselModule,
  ChartModule,
  CheckboxModule,
  ConfirmDialogModule,
  ConfirmationService,
  DeferModule,
  DialogModule,
  DragDropModule,
  DropdownModule,
  FieldsetModule,
  EditorModule,
  FileUploadModule,
  InputMaskModule,
  InputSwitchModule,
  InputTextareaModule,
  InputTextModule,
  ListboxModule,
  MenuModule,
  MessageModule,
  MessagesModule,
  MultiSelectModule,
  OrderListModule,
  OrganizationChartModule,
  OverlayPanelModule,
  PaginatorModule,
  PanelModule,
  PanelMenuModule,
  PickListModule,
  ProgressBarModule,
  ProgressSpinnerModule,
  RadioButtonModule,
  SelectButtonModule,
  SidebarModule,
  SliderModule,
  SpinnerModule,
  SplitButtonModule,
  StepsModule,
  TabMenuModule,
  TabViewModule,
  TieredMenuModule,
  ToggleButtonModule,
  TooltipModule,
  TreeModule,
  TreeTableModule,
  CardModule,
  ScrollPanelModule,
  ToolbarModule,
  ChipsModule,
} from 'primeng/primeng';
import { ToastModule } from 'primeng/toast';
import { TableModule } from 'primeng/table';
import { FullCalendarModule } from 'primeng/fullcalendar';
import { DataViewModule } from 'primeng/dataview';
import { DynamicDialogModule } from 'primeng/dynamicdialog';


@NgModule({
  declarations: [],
  providers: [ConfirmationService],
  imports: [
    ToastModule,
    TableModule,
    FullCalendarModule,
    DataViewModule,
    DynamicDialogModule,
    AccordionModule,
    AutoCompleteModule,
    BreadcrumbModule,
    ButtonModule,
    BlockUIModule,
    CalendarModule,
    CaptchaModule,
    CarouselModule,
    ChipsModule,
    ChartModule,
    CheckboxModule,
    ConfirmDialogModule,
    DeferModule,
    DragDropModule,
    EditorModule,
    DialogModule,
    DropdownModule,
    FieldsetModule,
    FileUploadModule,
    InputMaskModule,
    InputSwitchModule,
    InputTextareaModule,
    InputTextModule,
    ListboxModule,
    MenuModule,
    MessageModule,
    MessagesModule,
    MultiSelectModule,
    OrderListModule,
    OrganizationChartModule,
    OverlayPanelModule,
    PanelModule,
    PanelMenuModule,
    PaginatorModule,
    PickListModule,
    ProgressBarModule,
    ProgressSpinnerModule,
    RadioButtonModule,
    SelectButtonModule,
    SidebarModule,
    SliderModule,
    StepsModule,
    SpinnerModule,
    SplitButtonModule,
    TabMenuModule,
    TabViewModule,
    TieredMenuModule,
    ToggleButtonModule,
    TooltipModule,
    TreeModule,
    TreeTableModule,
    CardModule,
    ScrollPanelModule,
    ToolbarModule,

  ]
})
export class ApiSharedModule {
  static forRoot(): ModuleWithProviders {
    return {
      ngModule: ApiSharedModule,
    };
  }
}

